version: '3'

services:
  mariadb:
    image: 'mariadb'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - 'mariadb:/var/lib/mysql'

volumes:
  mariadb:
    driver: local
